run:
  go: "1.26"
  timeout: 5m

issues:
  exclude-dirs:
    - scratch
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - forcetypeassert
    - noctx
    - reassign
    - wastedassign

linters-settings:
  staticcheck:
    checks:
      - all
  errcheck:
    check-type-assertions: true
